export const jokesData = [
  { id: 1, joke: "Proč nemůžeš věřit schodům? Protože jsou vždycky zrádné." },
  { id: 2, joke: "Jak se jmenuje medvěd bez zubů? GumiMedvěd." },
  { id: 3, joke: "Proč se zavírá oční ordinace? Protože pacienti nevidí důvod, proč tam chodit." },
  { id: 4, joke: "Jaký je nejnebezpečnější druh pečiva? Zabijačková houska." },
  { id: 5, joke: "Proč rybář nekoupí nový prut? Protože má háček." },
  { id: 6, joke: "Jaký je nejlepší způsob, jak chytit zajíce? Stačí si počkat, až přijde velikonoční zloděj." },
  { id: 7, joke: "Jaký nápoj pije astronaut? Kosmopolitní." },
  { id: 8, joke: "Co řekne jedno vajíčko druhému? 'Koukni na sebe, jsi úplně na šlupce!'" },
  { id: 9, joke: "Proč si mléko dává brýle? Aby bylo plnotučné!" },
  { id: 10, joke: "Jaký je nejoblíbenější sport matematiků? Počítání bodů!" },
  { id: 11, joke: "Co udělá chleba, když se mu něco nelíbí? Okamžitě se rozkrájí." },
  { id: 12, joke: "Proč krávy nemají telefon? Protože by pořád jenom bučely!" },
  { id: 13, joke: "Jaký je nejlepší způsob, jak zabavit netopýra? Dej mu počítač a řekni mu, ať spustí Windows." },
  { id: 14, joke: "Proč měl lev nejhorší den v zoo? Protože ho celý den jenom štvěli!" },
  { id: 15, joke: "Jaký je oblíbený hudební nástroj strašidel? BUBNy." },
  { id: 16, joke: "Co říká kosmonaut, když jde na toaletu? 'Mám nutkání na malou oběžnou dráhu.'" },
  { id: 17, joke: "Proč si medvědi nikdy nevybavují své narozeniny? Protože mají zimní spánek." },
  { id: 18, joke: "Co si řeknou dvě kočky, když vidí psa? 'Tohle je vážně štěk!'" },
  { id: 19, joke: "Jak se nazývá utíkající zelenina? Běhrajče!" },
  { id: 20, joke: "Co řekl programátor, když mu došly kafe? 'Přepsání kódu nebude fungovat bez restartu.'" },
  { id: 21, joke: "Proč je tučňák tak dobrý v matematice? Protože vždycky najde správný úhel." },
  { id: 22, joke: "Jak se říká člověku, který jede na rotopedu? Cyklo-stacionář." },
  { id: 23, joke: "Co dělá stěna, když chce být nenápadná? Splývá s okolím." },
  { id: 24, joke: "Jak se zdraví dva elektrické vodiče? 'Ahoj, dráte!'" },
  { id: 25, joke: "Proč ptáci nemají sociální sítě? Protože mají problém s tweety!" }
];